// Generated by CoffeeScript 1.10.0
(function() {
  var NanikaStorage, debug,
    slice = [].slice;

  if (typeof require !== "undefined" && require !== null) {
    NanikaStorage = require('./NanikaStorage');
  } else if (typeof window !== "undefined" && window !== null) {
    NanikaStorage = window.NanikaStorage;
  }

  if (NanikaStorage == null) {
    NanikaStorage = {};
  }

  if (NanikaStorage.Backend == null) {
    NanikaStorage.Backend = {};
  }

  debug = false;

  NanikaStorage.Backend.FS = (function() {
    function FS(home, fs, path, Buffer) {
      this.home = home;
      this.fs = fs;
      this.path = path;
      this.Buffer = Buffer;
    }

    FS.prototype.ghost_base_path = function() {
      return this.path.join(this.home, 'ghost');
    };

    FS.prototype.balloon_base_path = function() {
      return this.path.join(this.home, 'balloon');
    };

    FS.prototype.shell_base_path = function(dirpath) {
      return this.path.join(this.ghost_path(dirpath), 'shell');
    };

    FS.prototype.ghost_path = function(dirpath) {
      return this.path.join(this.home, 'ghost', dirpath);
    };

    FS.prototype.balloon_path = function(dirpath) {
      return this.path.join(this.home, 'balloon', dirpath);
    };

    FS.prototype.ghost_master_path = function(dirpath) {
      return this.path.join(this.ghost_path(dirpath), 'ghost', 'master');
    };

    FS.prototype.shell_path = function(dirpath, shellpath) {
      return this.path.join(this.ghost_path(dirpath), 'shell', shellpath);
    };

    FS.prototype.base_profile_path = function() {
      return this.path.join(this.home, 'profile', 'base.profile.json');
    };

    FS.prototype.ghost_profile_path = function(dirpath) {
      return this.path.join(this.ghost_master_path(dirpath), 'profile', 'ghost.profile.json');
    };

    FS.prototype.balloon_profile_path = function(dirpath) {
      return this.path.join(this.balloon_path(dirpath), 'profile', 'balloon.profile.json');
    };

    FS.prototype.shell_profile_path = function(dirpath, shellpath) {
      return this.path.join(this.shell_path(dirpath, shellpath), 'profile', 'shell.profile.json');
    };

    FS.prototype._accessor = function(target, directory, merge) {
      var promise;
      promise = new Promise(function(resolve) {
        return resolve();
      });
      if (directory != null) {
        if (!merge) {
          promise = promise.then((function(_this) {
            return function() {
              return _this._rmAll(target);
            };
          })(this));
        }
        promise = promise.then((function(_this) {
          return function() {
            return _this._DirectoryToFS(target, directory);
          };
        })(this));
      }
      promise = promise.then((function(_this) {
        return function() {
          return _this._FSToDirectory(target);
        };
      })(this));
      return promise;
    };

    FS.prototype.ghost = function(dirpath, directory, merge) {
      var target;
      target = this.ghost_path(dirpath);
      return this._accessor(target, directory, merge);
    };

    FS.prototype.balloon = function(dirpath, directory, merge) {
      var target;
      target = this.balloon_path(dirpath);
      return this._accessor(target, directory, merge);
    };

    FS.prototype.ghost_master = function(dirpath, directory, merge) {
      var target;
      target = this.ghost_master_path(dirpath);
      return this._accessor(target, directory, merge);
    };

    FS.prototype.shell = function(dirpath, shellpath, directory, merge) {
      var target;
      target = this.shell_path(dirpath, shellpath);
      return this._accessor(target, directory, merge);
    };

    FS.prototype._profile = function(target, profile) {
      var dir;
      if (profile != null) {
        dir = this.path.dirname(target);
        return this._mkpath(dir).then((function(_this) {
          return function() {
            return new Promise(function(resolve, reject) {
              return _this.fs.writeFile(target, JSON.stringify(profile), {
                encoding: 'utf8'
              }, function(err) {
                if (err != null) {
                  return reject(err);
                } else {
                  return resolve(profile);
                }
              });
            });
          };
        })(this));
      } else {
        return new Promise((function(_this) {
          return function(resolve, reject) {
            return _this.fs.readFile(target, {
              encoding: 'utf8'
            }, function(err, data) {
              if (err != null) {
                return resolve({});
              } else {
                return resolve(data.length ? JSON.parse(data) : {});
              }
            });
          };
        })(this));
      }
    };

    FS.prototype.base_profile = function(profile) {
      var target;
      target = this.base_profile_path();
      return this._profile(target, profile);
    };

    FS.prototype.ghost_profile = function(dirpath, profile) {
      var target;
      target = this.ghost_profile_path(dirpath);
      return this._profile(target, profile);
    };

    FS.prototype.balloon_profile = function(dirpath, profile) {
      var target;
      target = this.balloon_profile_path(dirpath);
      return this._profile(target, profile);
    };

    FS.prototype.shell_profile = function(dirpath, shellpath, profile) {
      var target;
      target = this.shell_profile_path(dirpath, shellpath);
      return this._profile(target, profile);
    };

    FS.prototype.ghosts = function() {
      var target;
      target = this.ghost_base_path();
      return this._readdir(target);
    };

    FS.prototype.balloons = function() {
      var target;
      target = this.balloon_base_path();
      return this._readdir(target);
    };

    FS.prototype.shells = function(dirpath) {
      var target;
      target = this.shell_base_path(dirpath);
      return this._readdir(target);
    };

    FS.prototype._elements_name = function(target, type) {
      return this._readdir(target).then((function(_this) {
        return function(items) {
          var item, itemtarget, j, len, promises;
          promises = [];
          for (j = 0, len = items.length; j < len; j++) {
            item = items[j];
            itemtarget = _this.path.join(target, item);
            promises.push(_this._FSFileToDirectory(itemtarget, type));
          }
          return Promise.all(promises).then(function(directories) {
            if (type === 'install.txt') {
              return directories.map(function(directory) {
                return directory.install.name;
              }).sort();
            } else {
              return directories.map(function(directory) {
                return directory.descript.name;
              }).sort();
            }
          });
        };
      })(this));
    };

    FS.prototype.ghost_names = function() {
      var target;
      target = this.ghost_base_path();
      return this._elements_name(target, 'install.txt');
    };

    FS.prototype.balloon_names = function() {
      var target;
      target = this.balloon_base_path();
      return this._elements_name(target, 'install.txt');
    };

    FS.prototype.shell_names = function(dirpath) {
      var target;
      target = this.shell_base_path(dirpath);
      return this._elements_name(target, 'descript.txt');
    };

    FS.prototype.ghost_name = function(dirpath) {
      return this.ghost_install(dirpath).then(function(install) {
        return install.name;
      });
    };

    FS.prototype.balloon_name = function(dirpath) {
      return this.balloon_install(dirpath).then(function(install) {
        return install.name;
      });
    };

    FS.prototype.shell_name = function(dirpath, shellpath) {
      return this.shell_descript(dirpath, shellpath).then(function(descript) {
        return descript.name;
      });
    };

    FS.prototype.ghost_install = function(dirpath) {
      var target;
      target = this.ghost_path(dirpath);
      return this._FSFileToDirectory(target, 'install.txt').then(function(directory) {
        return directory.install;
      });
    };

    FS.prototype.balloon_install = function(dirpath) {
      var target;
      target = this.balloon_path(dirpath);
      return this._FSFileToDirectory(target, 'install.txt').then(function(directory) {
        return directory.install;
      });
    };

    FS.prototype.shell_install = function(dirpath, shellpath) {
      var itempath, target;
      target = this.shell_path(dirpath, shellpath);
      itempath = this.path.join(target, 'install.txt');
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.fs.stat(itempath, function(err, stats) {
            if (err != null) {
              return resolve(false);
            } else {
              return resolve(true);
            }
          });
        };
      })(this)).then((function(_this) {
        return function(exists) {
          if (exists) {
            return _this._FSFileToDirectory(target, 'install.txt').then(function(directory) {
              return directory.install;
            });
          }
        };
      })(this));
    };

    FS.prototype.ghost_descript = function(dirpath) {
      var target;
      target = this.ghost_master_path(dirpath);
      return this._FSFileToDirectory(target, 'descript.txt').then(function(directory) {
        return directory.descript;
      });
    };

    FS.prototype.balloon_descript = function(dirpath) {
      var target;
      target = this.balloon_path(dirpath);
      return this._FSFileToDirectory(target, 'descript.txt').then(function(directory) {
        return directory.descript;
      });
    };

    FS.prototype.shell_descript = function(dirpath, shellpath) {
      var target;
      target = this.shell_path(dirpath, shellpath);
      return this._FSFileToDirectory(target, 'descript.txt').then(function(directory) {
        return directory.descript;
      });
    };

    FS.prototype.delete_ghost = function(dirpath) {
      var target;
      target = this.ghost_path(dirpath);
      return this._rmAll(target);
    };

    FS.prototype.delete_balloon = function(dirpath) {
      var target;
      target = this.balloon_path(dirpath);
      return this._rmAll(target);
    };

    FS.prototype._filter_elements = function(target, paths) {
      var filter_paths;
      filter_paths = {};
      paths.forEach((function(_this) {
        return function(item) {
          var itemdir, results;
          filter_paths[item] = true;
          results = [];
          while (true) {
            itemdir = _this.path.dirname(item);
            if (itemdir === item) {
              break;
            }
            item = itemdir;
            results.push(filter_paths[item] = true);
          }
          return results;
        };
      })(this));
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.fs.stat(target, function(err, stats) {
            if (err != null) {
              return resolve(false);
            } else {
              return resolve(true);
            }
          });
        };
      })(this)).then((function(_this) {
        return function(exists) {
          if (exists) {
            return _this._readdirAll(target).then(function(items) {
              var item, itempath, j, len, rmdirs, rmfiles, selects;
              selects = [];
              rmfiles = [];
              rmdirs = [];
              for (j = 0, len = items.length; j < len; j++) {
                item = items[j];
                itempath = _this.path.join(target, item);
                if (!filter_paths[item]) {
                  (function(itempath) {
                    return selects.push(_this._stat(itempath).then(function(stats) {
                      if (stats.isFile()) {
                        return rmfiles.push(itempath);
                      } else {
                        return rmdirs.push(itempath);
                      }
                    }));
                  })(itempath);
                }
              }
              return Promise.all(selects).then(function() {
                return Promise.all(rmfiles.map(function(file) {
                  return _this._unlink(file);
                }));
              }).then(function() {
                return _this._rmdirs(rmdirs);
              });
            });
          }
        };
      })(this));
    };

    FS.prototype.filter_ghost = function(dirpath, paths) {
      var target;
      target = this.ghost_path(dirpath);
      return this._filter_elements(target, paths);
    };

    FS.prototype.filter_balloon = function(dirpath, paths) {
      var target;
      target = this.balloon_path(dirpath);
      return this._filter_elements(target, paths);
    };

    FS.prototype.filter_shell = function(dirpath, shellpath, paths) {
      var target;
      target = this.shell_path(dirpath, shellpath);
      return this._filter_elements(target, paths);
    };

    FS.prototype._readdir = function(target) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.fs.readdir(target, function(err, items) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve(items);
            }
          });
        };
      })(this));
    };

    FS.prototype._readdirAll = function(target) {
      var readdir;
      readdir = (function(_this) {
        return function(dir, basedir) {
          return new Promise(function(resolve, reject) {
            return _this.fs.readdir(dir, function(err, entries) {
              var entry, j, len, promises;
              if (err != null) {
                return reject(err);
              }
              promises = [];
              for (j = 0, len = entries.length; j < len; j++) {
                entry = entries[j];
                promises.push((function(entry_path) {
                  return _this._stat(entry_path).then(function(stats) {
                    if (stats.isDirectory()) {
                      return readdir(entry_path, basedir).then(function(entry_paths) {
                        return [_this.path.relative(basedir, entry_path)].concat(slice.call(entry_paths));
                      });
                    } else {
                      return [_this.path.relative(basedir, entry_path)];
                    }
                  });
                })(_this.path.join(dir, entry)));
              }
              return Promise.all(promises).then(function(entry_paths_list) {
                var a_entry_paths, entry_paths, k, len1;
                entry_paths = [];
                for (k = 0, len1 = entry_paths_list.length; k < len1; k++) {
                  a_entry_paths = entry_paths_list[k];
                  entry_paths = entry_paths.concat(a_entry_paths);
                }
                return resolve(entry_paths);
              });
            });
          });
        };
      })(this);
      return readdir(target, target);
    };

    FS.prototype._stat = function(target) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.fs.stat(target, function(err, stats) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve(stats);
            }
          });
        };
      })(this));
    };

    FS.prototype._unlink = function(target) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.fs.unlink(target, function(err) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve();
            }
          });
        };
      })(this));
    };

    FS.prototype._rmdir = function(target) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.fs.rmdir(target, function(err) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve();
            }
          });
        };
      })(this));
    };

    FS.prototype._rmdirs = function(targets) {
      var current_hierarchy, hierarchy, j, k, len, len1, new_target_path, rmdirs, target, target_path, target_path_token, target_path_tokens, token, walk;
      hierarchy = {
        children: {}
      };
      for (j = 0, len = targets.length; j < len; j++) {
        target = targets[j];
        target_path = this.path.resolve(target);
        target_path_tokens = [];
        while (true) {
          token = this.path.basename(target_path);
          new_target_path = this.path.dirname(target_path);
          if (new_target_path === target_path) {
            break;
          }
          target_path_tokens.unshift(token);
          target_path = new_target_path;
        }
        current_hierarchy = hierarchy;
        for (k = 0, len1 = target_path_tokens.length; k < len1; k++) {
          target_path_token = target_path_tokens[k];
          if (current_hierarchy.children[target_path_token] == null) {
            current_hierarchy.children[target_path_token] = {
              children: {}
            };
          }
          current_hierarchy = current_hierarchy.children[target_path_token];
        }
        current_hierarchy.remove = true;
      }
      rmdirs = [];
      walk = (function(_this) {
        return function(current_hierarchy, hierarchy_path) {
          var child, l, len2, ref, results;
          if (current_hierarchy.remove) {
            return rmdirs.push(hierarchy_path);
          } else {
            ref = Object.keys(current_hierarchy.children);
            results = [];
            for (l = 0, len2 = ref.length; l < len2; l++) {
              child = ref[l];
              results.push(walk(current_hierarchy.children[child], _this.path.join(hierarchy_path, child)));
            }
            return results;
          }
        };
      })(this);
      walk(hierarchy, '/');
      return Promise.all(rmdirs.map((function(_this) {
        return function(dir) {
          return _this._rmdirAll(dir);
        };
      })(this)));
    };

    FS.prototype._rmdirAll = function(target) {
      return this._readdirAll(target).then((function(_this) {
        return function(dirs) {
          var dir, fn, j, len, promise, ref;
          dirs.unshift('');
          promise = new Promise(function(resolve) {
            return resolve();
          });
          ref = dirs.reverse();
          fn = function(dir) {
            return promise = promise.then(function() {
              return _this._rmdir(_this.path.join(target, dir));
            });
          };
          for (j = 0, len = ref.length; j < len; j++) {
            dir = ref[j];
            fn(dir);
          }
          return promise;
        };
      })(this));
    };

    FS.prototype._rmAll = function(target) {
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.fs.stat(target, function(err, stats) {
            if (err != null) {
              return resolve(false);
            } else {
              return resolve(true);
            }
          });
        };
      })(this)).then((function(_this) {
        return function(exists) {
          if (exists) {
            return _this._readdirAll(target).then(function(items) {
              var fn, item, itempath, j, len, rmdirs, rmfiles, selects;
              selects = [];
              rmfiles = [];
              rmdirs = [];
              items.unshift('');
              fn = function(itempath) {
                return selects.push(_this._stat(itempath).then(function(stats) {
                  if (stats.isFile()) {
                    return rmfiles.push(itempath);
                  } else {
                    return rmdirs.push(itempath);
                  }
                }));
              };
              for (j = 0, len = items.length; j < len; j++) {
                item = items[j];
                itempath = _this.path.join(target, item);
                fn(itempath);
              }
              return Promise.all(selects).then(function() {
                return Promise.all(rmfiles.map(function(file) {
                  return _this._unlink(file);
                }));
              }).then(function() {
                return _this._rmdirs(rmdirs);
              });
            });
          }
        };
      })(this));
    };

    FS.prototype._mkpath = function(target) {
      var mkdir, mode;
      mode = parseInt("0777", 8);
      mkdir = (function(_this) {
        return function(target) {
          return new Promise(function(resolve, reject) {
            return _this.fs.stat(target, function(err, stats) {
              if (err != null) {
                return resolve(false);
              } else {
                return resolve(true);
              }
            });
          }).then(function(exists) {
            var deep;
            if (!exists) {
              deep = _this.path.dirname(target);
              if (deep !== target) {
                return mkdir(deep).then(function() {
                  return new Promise(function(resolve, reject) {
                    return _this.fs.mkdir(target, mode, function(err) {
                      return resolve();
                    });
                  });
                });
              }
            }
          });
        };
      })(this);
      return mkdir(target);
    };

    FS.prototype._DirectoryToFS = function(target, directory) {
      var fn, item, promises;
      promises = [];
      fn = (function(_this) {
        return function(item) {
          var dir, itempath, value;
          value = directory.files[item];
          itempath = _this.path.join(target, item);
          if (value.isFile()) {
            dir = _this.path.dirname(itempath);
            return promises.push(_this._mkpath(dir).then(function() {
              return new Promise(function(resolve, reject) {
                return _this.fs.writeFile(itempath, _this._fromArrayBuffer(value.buffer()), {}, function(err) {
                  if (err != null) {
                    return reject(err);
                  } else {
                    return resolve();
                  }
                });
              });
            }));
          } else {
            return promises.push(_this._mkpath(itempath).then(function() {}));
          }
        };
      })(this);
      for (item in directory.files) {
        fn(item);
      }
      return Promise.all(promises).then((function(_this) {
        return function() {};
      })(this));
    };

    FS.prototype._FSToDirectory = function(target) {
      var directory;
      directory = {};
      return this._readdirAll(target).then((function(_this) {
        return function(items) {
          var fn, item, j, len, promises;
          promises = [];
          fn = function(item) {
            var itempath;
            itempath = _this.path.join(target, item);
            return promises.push(_this._stat(itempath).then(function(stats) {
              if (stats.isFile()) {
                return new Promise(function(resolve, reject) {
                  return _this.fs.readFile(itempath, {}, function(err, buffer) {
                    if (err != null) {
                      return reject(err);
                    } else {
                      return resolve(buffer);
                    }
                  });
                }).then(function(buffer) {
                  return directory[item] = _this._toArrayBuffer(buffer);
                });
              }
            }));
          };
          for (j = 0, len = items.length; j < len; j++) {
            item = items[j];
            fn(item);
          }
          return Promise.all(promises).then(function() {
            return new NanikaDirectory(directory);
          });
        };
      })(this));
    };

    FS.prototype._FSFileToDirectory = function(target, item) {
      var itempath;
      itempath = this.path.join(target, item);
      return new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.fs.readFile(itempath, {}, function(err, buffer) {
            if (err != null) {
              return reject(err);
            } else {
              return resolve(buffer);
            }
          });
        };
      })(this)).then((function(_this) {
        return function(buffer) {
          var directory;
          directory = {};
          directory[item] = _this._toArrayBuffer(buffer);
          return new NanikaDirectory(directory);
        };
      })(this));
    };

    FS.prototype._toArrayBuffer = function(buffer) {
      var abuffer, i, view;
      abuffer = new ArrayBuffer(buffer.length);
      view = new Uint8Array(abuffer);
      i = 0;
      while (i < buffer.length) {
        view[i] = buffer.readUInt8(i);
        i++;
      }
      return abuffer;
    };

    FS.prototype._fromArrayBuffer = function(abuffer) {
      var error;
      try {
        return new this.Buffer(new Uint8Array(abuffer));
      } catch (error) {
        return new this.Buffer(abuffer);
      }
    };

    return FS;

  })();

  if ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null) {
    module.exports = NanikaStorage;
  } else if ((typeof window !== "undefined" && window !== null ? window.Ikagaka : void 0) != null) {
    window.Ikagaka.NanikaStorage = NanikaStorage;
  } else if (typeof window !== "undefined" && window !== null) {
    window.NanikaStorage = NanikaStorage;
  }

}).call(this);
